[package]
name = "horse-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-master = "3.1.3"
regex = "1"
lazy_static = "1.4.0"
clipboard = "0.5.0"
